version: "3.9"  # v1.27.0 からはオプション
services:
  web:
    build: .
    ports:
      - "3100:3000"
    volumes:
      - .:/app
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
